name              'webserver'
maintainer        'Alex Bartsch'
maintainer_email  'mail@alexbartsch.de'
license           'Apache 2.0'
description       'Installs a webserver'
version           '1.0.0'